### ISSUE TITLE
adblock bait in haaretz changed again

### ISSUE THREAD

**Issue by niraizik** [ABPIsrael/EasyListHebrew#104]
haaretz.co.il changed their ADB bait.
this is what i can see:
cssClass: "pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links"

This rule seems to work:
@@||haaretz.co.il^$elemhide

or more specifically:
haaretz.co.il#@#.pub_300x250
haaretz.co.il#@#.pub_300x250m
haaretz.co.il#@#.pub_728x90
haaretz.co.il#@#.text-ad
haaretz.co.il#@#.textAd
haaretz.co.il#@#.text_ad
haaretz.co.il#@#.text_ads
haaretz.co.il#@#.text-ads
haaretz.co.il#@#.text-ad-links

![2016-04-21 16_00_00 logger](https://cloud.githubusercontent.com/assets/8015136/14709690/b2cfc2aa-07da-11e6-9a0f-66744a53bdcc.png)

**Comment by yuvadm** [comment]
@niraizik those rules work for me as well. requires manual cookie deletion though, as usual.

**Comment by niraizik** [comment]
@yuvadm for me it works w/o deleting any cookies. it just think I've disabled the ad blocker.

**Comment by almog123** [comment]
https://goo.gl/JvKpyi Im getting it too.

**Comment by niraizik** [comment]
@EasyListIsrael if you can't reproduce it, it's probably because they block only certain percent of the time you visit them. there is a cookie called skipAdblockRedirect. If you delete it and reload the page you could get redirected to the blocking page. you maybe need to do it a few times until to get "lucky" and get redirected to the blocking page.

**Comment by niraizik** [comment]
we can close it due to https://github.com/ABPIsrael/EasyListHebrew/commit/379bf30cd58b6cda4c8fd3f9a2ee5ef4a819c7c8

**Comment by yuvadm** [comment]
@niraizik are you sure? i'm still seeing the block page. I'm getting `/hblocked` on the URL, which is new.

**Comment by niraizik** [comment]
@yuvadm try deleting every thing under Local Storage also. check your adblock log to see if it still blocking their bait element, maybe it didn't updated to latest list version.

**Comment by yuvadm** [comment]
@niraizik good call, localstorage worked

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#103
