### ISSUE TITLE
Ynet new ads

### ISSUE THREAD

**Issue by AdHelper** [ABPIsrael/EasyListHebrew#106]
new ads on ynet homepage.
`ynet.co.il###PromoLightbox1024-1`
`ynet.co.il##.PromoLightbox1024Span2-1`
`ynet.coi.il##div[style="height:119px !important"]`

**Comment by AdHelper** [comment]
any news? 7 days have been past.

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#106
