### ISSUE TITLE
Ha'aretz modal ad not blocked

### ISSUE THREAD

**Issue by sillyfly** [ABPIsrael/EasyListHebrew#107]
Ha'aretz recently added a new modal subscription ad which AdBlock seems unable to recognize/block. 
I have this rule 5 times already from trying to block it: 

    www.haaretz.co.il##DIV[class="modal-wrapper modal-wrapper--fixed modal-wrapper--dark"]

but it still shows up every time.

**Comment by EasyListIsrael** [comment]
check for malware
http://malwaretips.com/blogs/remove-offers-by-context-com/
https://easylist.adblockplus.org/blog/2013/03/09/ads-caused-by-malware-or-adware-extensions-or-plugins

**Comment by sillyfly** [comment]
I'm on Linux, so all of the tools mentioned are irrelevant. I highly doubt this is due to malware, as it's Ha'aretz's own ad, and I have no other problems with any other site. Unless you think Ha'aretz employs malware to inject their ads over their own site.

**Comment by AdHelper** [comment]
same here:
https://goo.gl/JvKpyi

**Comment by EasyListIsrael** [comment]
self advertising is not blocked using adblock

**Comment by niraizik** [comment]
@sillyfly try this, it works for me
www.haaretz.co.il##.modal-wrapper

**Comment by IsraeliAdblocker** [comment]
which browser are you using? how can I reproduce the issue?

**Comment by mderazon** [comment]
I can confirm it reproduces on Chrome for Mac version 50.0.2661.102 (64-bit)

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#19

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#107
