### ISSUE TITLE
Ynet wobi ad

### ISSUE THREAD

**Issue by ecc101** [ABPIsrael/EasyListHebrew#111]
http://www.ynet.co.il/articles/0,7340,L-4800073,00.html

![capture](https://cloud.githubusercontent.com/assets/19220469/15067015/203af192-1376-11e6-93e9-8ac9889b69ed.PNG)

**Comment by EasyListIsrael** [comment]
what browser?
if you refresh the page the ads disappear?

**Comment by ecc101** [comment]
- Chrome.
- No, still there at the top right corner.

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#111
