### ISSUE TITLE
Banner in www.inn.co.il/

### ISSUE THREAD

**Issue by Yaron10** [ABPIsrael/EasyListHebrew#112]
Hello,

Could you please block the banner at the bottom of http://www.inn.co.il/?

Thank you.

**Comment by niraizik** [comment]
@Yaron10 Try this
www.inn.co.il###divB800Out

**Comment by Yaron10** [comment]
@niraizik,

That doesn't work. `||a7.org/resize/info/1000x60/*` removes the banner but the "X" is still there.

Thank you.

**Comment by niraizik** [comment]
@Yaron10 can you check if your banner have a different id name, because this works for me.

**Comment by Yaron10** [comment]
The ID is the same.
Could you please post the entire/exact filter you're using?

Thank you.

**Comment by Yaron10** [comment]
`www.inn.co.il###divB800` works for me.

Thank you very much.

**Comment by Yaron10** [comment]
@EasyListIsrael,

Thank you. I appreciate your work.

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#112
