### ISSUE TITLE
Ynet ads

### ISSUE THREAD

**Issue by AdHelper** [ABPIsrael/EasyListHebrew#113]
ynet.co.il has huge ads all over the pages
same as globes
http://www.ynet.co.il/articles/0,7340,L-4799712,00.html

the current domain is: kmrnkjer.xyz

printscreen: https://goo.gl/jJ8lOr

globes.co.il ads are keep coming also.
best way to block them is blocking: s3.amazonaws.com $script

**Comment by EasyListIsrael** [comment]
https://github.com/ABPIsrael/EasyListHebrew/issues/110

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#113
