### ISSUE TITLE
Ads on Walla sports

### ISSUE THREAD

**Issue by skyl4s** [ABPIsrael/EasyListHebrew#116]
with opera's internal ad-blocker and easylist. 

![wallasports](https://cloud.githubusercontent.com/assets/19342346/15242100/bf0edab4-18fc-11e6-8c7b-62732357fef2.jpg)

**Comment by AdHelper** [comment]
URL please.

**Comment by skyl4s** [comment]
http://sports.walla.co.il/

**Comment by IsraeliAdblocker** [comment]
Are you using easylist hebrew? I've checked from FF+CH and I can't find the ads you are talking about.

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#116
