### ISSUE TITLE
Problem enter to Sport Links in Ynet

### ISSUE THREAD

**Issue by roni14** [ABPIsrael/EasyListHebrew#117]
I use Adblock Plus 2.7.3
All websites all works well.
The only place that i can not enter it :  links (Sport Links) in Ynet 
This is the linke of the Website Ynet:
http://www.ynet.co.il/home/0,7340,L-8,00.html
Even Ynet  Website i can enter anywhere except for from sports links.
Here are some examples that I can not enter:
http://www.ynet.co.il/articles/0,7340,L-4804008,00.html
http://www.ynet.co.il/articles/0,7340,L-4803918,00.html
http://www.ynet.co.il/articles/0,7340,L-4803919,00.html
There are many more.
Only if I disable EasyListHebrew in Adblock Plus i can enter.
There is a possibility to solve the problem?
I use Adblock Plus 2.7.3
All websites all works well.
The only place that i can not enter it :  links (Sport Links) in Ynet 
This is the linke of the Website Ynet:
http://www.ynet.co.il/home/0,7340,L-8,00.html
Even Ynet  Website i can enter anywhere except for from sports links.
Here are some examples that I can not enter:
http://www.ynet.co.il/articles/0,7340,L-4804008,00.html
http://www.ynet.co.il/articles/0,7340,L-4803918,00.html
http://www.ynet.co.il/articles/0,7340,L-4803919,00.html
There are many more.
Only if I disable EasyListHebrew in Adblock Plus i can enter.
There is a possibility to solve the problem?

**Comment by IsraeliAdblocker** [comment]
even with the newest APB and hebrew list, I can't reproduce your problem, which browser are you using?

**Comment by roni14** [comment]
יובל שלום,
על הבעייה כתבתי גם בפורום של FireFox, הנה:
http://community.mozilla.org.il/viewtopic.php?f=9&t=12471&p=61798#p61798

לא משנה באיזה לינק בYnet (רק בקטגוריית הספורט) כשאני מנסה להכנס ללינק זה
מנסה להתחבר וזהו - נתקע (זה התחיל מערב יום העצמאות)
אין שום בעייה עם שאר הלינקים בכל האתרים כולל Ynet.
חשבתי שזה רק ב  - Adblock Plus , הסרתי אותו
והתקנתי אתמול את  uBlock Origin 1.7.0 וגם שם בדיוק אותה תופעה וזה רק ברשימת
המסננים שלך, כשאני מבטל את ה - V ב EasyListHebrew אני נכנס ללינקים בלי שום
בעייה (אבל אז כמובן יש את הפרסומות).

תודה על הנסיון לעזור,
מוטי.
 
 
-------Original Message-------
 
From: Yuval
Date: 17/05/2016 15:27:33
To: ABPIsrael/EasyListHebrew
Cc: roni14;  Author
Subject: Re: [ABPIsrael/EasyListHebrew] Problem enter to Sport Links in Ynet
(#117)
 
even with the newest APB and hebrew list, I can't reproduce your problem,
which browser are you using?

**Comment by IsraeliAdblocker** [comment]
Please share a full screenshot of the problematic page and explain what are you clicking on.
I'm testing it now and everything seems to be fine.

**Comment by roni14** [comment]
יובל שלום,

הנה התמונות וההסברים:
תמונה 1 - נכנסתי ל Ynet .
תמונה 2 -  אלה הלינקים של ספורט ב Ynet ואני מנסה להכנס ללינק (מתחת לתמונה)
תמונה 3 -  אי אפשר להכנס, זה נכנס ללולאה וזה מה שמקבלים (כל הזמן העיגול
מימין להתחברות מסתובב) והדף נותר לבן.
אי אפשר גם לחזור אחרוה ל Ynet זה תקוע בלולאה, על מנת להכנס ל Ynet אני חייב
להכנס דרך הסימנייה או מועדפים.
תמונה 4 -  אני מנסה להכנס ללינק נוסף.
תמונה 5 -  בדיוק כמו בתמונה 3.
תמונה 6 - נכנסתי להגדרות של AdBlock על מנת להוריד את סימן ה - V ב EasyList.
תמונה 7 -  אני מנסה להכנס שוב לאחד מהלינקים בYnet ספורט.
תמונה 8 - אין שום בעייה נכנסים מיד אבל עם כל הפרסומות. (בצד ימין יש את
הלשונית של ההתחברות ולמרות שהורדתי את סימן ה - V ב EasyList זה תקוע בלולאה
ולא מצליח להתחבר.

בברכה,
מוטי. 

 
 
 
-------Original Message-------
 
From: Yuval
Date: 17/05/2016 15:45:54
To: ABPIsrael/EasyListHebrew
Cc: roni14;  Author
Subject: Re: [ABPIsrael/EasyListHebrew] Problem enter to Sport Links in Ynet
(#117)
 
Please share a full screenshot of the problematic page and explain what are
you clicking on.
I'm testing it now and everything seems to be fine.

**Comment by IsraeliAdblocker** [comment]
I can't see any pictures.

**Comment by roni14** [comment]
כל מה שאני כותב זה דרך המייל, רק לאחר ששלחתי הבנתי שזה עולה מיד גם ל -
GitHub ללא התמונות שכן נשלחו באמצעות המייל , לכן ערכתי את הודעתי הקודמת
והוספתי לינקים של התמונות 1 -8 בהתאם לסדר. 
התנצלותי.
 
 
 
 
-------Original Message-------
 
From: Yuval
Date: 17/05/2016 18:11:15
To: ABPIsrael/EasyListHebrew
Cc: roni14;  Author
Subject: Re: [ABPIsrael/EasyListHebrew] Problem enter to Sport Links in Ynet
(#117)
 
I can't see any pictures.

**Comment by IsraeliAdblocker** [comment]
Please do the following:
1. disable all your other extensions
2. re-install ABP and update all your filters
3. go to a problematic page then click on ABP icon, then report issue and place your report issue link here.

**Comment by roni14** [comment]
שלחתי דיווח וזאת הכתובת שקיבלתי:
https://reports.adblockplus.org/a2f937d8-0d59-4e7f-8665-6e4b43c887da

כל מה שביקשת נעשה (סעיפים 1-3). 
 
 
 
 
-------Original Message-------
 
From: Yuval
Date: 17/05/2016 18:26:44
To: ABPIsrael/EasyListHebrew
Cc: roni14;  Author
Subject: Re: [ABPIsrael/EasyListHebrew] Problem enter to Sport Links in Ynet
(#117)
 
Please do the following:
1. Disable all your other extensions
2. re-install ABP and update all your filters
3. go to a problematic page then click on ABP icon, then report issue and
place your report issue link here.

**Comment by IsraeliAdblocker** [comment]
you didn't done 1, I can see that you are running another extensions that may cause this issue: 
Firefox Hello	1.2.6	extension
Multi-process staged rollout	1.0	extension
Pocket	1.0	extension

**Comment by IsraeliAdblocker** [comment]
I've checked on archive.org and the only script that was added to ynet.co.il on independence day was the big ugly JS script that is presented only on SPORT Ynet category and pages, I guess that it is somehow related to this issue (which I can't manage to reproduce no matter what), so I will suggest the following filter for you which will only work with Ublock currently:
`ynet.co.il##script:contains(Number.prototype.toJSON=Boolean.prototype)`

**Comment by roni14** [comment]
אין לי מושג מה זאת רשימת המסננים שרשמת כאן, כל המסננים כפי שביקשת עד עתה
מנוטרלים, מצורפת  תמונה כהוכחה לכך,
מעבר לכך אין לי מושג מה אני עושה עם מה שנתת  כוונתי לזה:
Ynet.co.IL##script:contains(Number.prototype.toJSON=Boolean.prototype) 
 
 
 
 
-------Original Message-------
 
From: Yuval
Date: 17/05/2016 19:16:07
To: ABPIsrael/EasyListHebrew
Cc: roni14;  Author
Subject: Re: [ABPIsrael/EasyListHebrew] Problem enter to Sport Links in Ynet
(#117)
 
you didn't done 1, I can see that you are running another extensions that
may cause this issue: 
Firefox Hello 1.2.6 extension
Multi-process staged rollout 1.0 extension
Pocket 1.0 extension

**Comment by EasyListHebrew** [comment]
hi
try disabling the filters
||s3.amazonaws.com^$script,domain=ynet.co.il
||faweprsdf.pw^$domain=ynet.co.il,third-party

**Comment by IsraeliAdblocker** [comment]
Have someone here managed to reproduce this? I've tried both in FF and CH newest versions, and with Mac along with WIN 7, nothing for me.

in order to place a new filter in Ublock Origin, right click on Ublock Origin icon on your extensions toolbar, then click on "Options" then click on "My Filters" and add the filter to there, then click on "apply changes".

**Comment by roni14** [comment]
I disabled what you asked and now it's O.K:
||s3.amazonaws.com^$script,domain=ynet.co.IL
||faweprsdf.pw^$domain=ynet.co.IL,third-party
But now the problem is the pop up and the adverts:
http://www.siz.co.il/my.php?i=dj3zim2ioymz.gif

 
 
 
 
-------Original Message-------
 
From: AdBlock Plus Israel | EasyList Hebrew
Date: 17/05/2016 21:03:38
To: ABPIsrael/EasyListHebrew
Cc: roni14;  Author
Subject: Re: [ABPIsrael/EasyListHebrew] Problem enter to Sport Links in Ynet
(#117)
 
hi
try disabling the filters
||s3.amazonaws.com^$script,domain=ynet.co.il
||faweprsdf.pw^$domain=ynet.co.il,third-party

**Comment by IsraeliAdblocker** [comment]
Have you tried my suggestion with Ublock Origin?

**Comment by roni14** [comment]
Everything works great now,
I can get in to all the links including Ynet Sport.
I removed (  complete removal ) FireFox and I reinstalled everything.
I installed uBlock Origin 1.7.0
Thanks for all  help

**Comment by IsraeliAdblocker** [comment]
Great :)
