### ISSUE TITLE
Ads on globes 

### ISSUE THREAD

**Issue by freeinternet16** [ABPIsrael/EasyListHebrew#118]
Hi, 
the same technique like in Ynet. please block http://loopmaze.com/

http://www.globes.co.il/news/article.aspx?did=1001124924

![image](https://cloud.githubusercontent.com/assets/17808973/15362891/75cfbc8e-1d1f-11e6-9436-0d014c652812.png)

Thanks!

**Comment by freeinternet16** [comment]
In addtion: 

![image](https://cloud.githubusercontent.com/assets/17808973/15363678/273a0694-1d22-11e6-9c88-babc6342e4b2.png)

**Comment by freeinternet16** [comment]
@EasyListHebrew ?

**Comment by IsraeliAdblocker** [comment]
Found & added.

**Comment by freeinternet16** [comment]
Thanks!

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#118
