### ISSUE TITLE
Ads in Globes

### ISSUE THREAD

**Issue by degoltz** [ABPIsrael/EasyListHebrew#119]
http://www.globes.co.il/news/article.aspx?did=1001124777
I see a banner in the top of the page,
4 ads on the left

![image](https://cloud.githubusercontent.com/assets/5446526/15408231/cb3c7600-1e17-11e6-8ef0-770f0b29327d.png)
![image](https://cloud.githubusercontent.com/assets/5446526/15408244/dbfdf464-1e17-11e6-8cd6-672140f5bb08.png)

**Comment by degoltz** [comment]
My filters:
![image](https://cloud.githubusercontent.com/assets/5446526/15408291/20502d30-1e18-11e6-833e-bf39c4b5f1e1.png)

**Comment by freeinternet16** [comment]
The same guys like ynet... changing domains. Just cat and mouse game. 
we need to find some generic rule here. 
this time they're using domain name: **klnrew.site** (always from the same IP - 5.100.252.181 - Sitting in Haifa). 
@EasyListIsrael - please block it.

**Comment by IsraeliAdblocker** [comment]
should be good now.

**Comment by freeinternet16** [comment]
Thanks, but - 

They chanced it again - now they use this domain - dascasdw.xyz. @IsraeliAdblocker - please add this domain into the list.
 
Or you can add -   *.xyz^$domain=globes.co.il,third-party

In addtion, please add @@||globes.co.il^$genericblock to the list as well. 

:)

**Comment by IsraeliAdblocker** [comment]
I can't see any reason why adding `@@||globes.co.il^$genericblock` should help.
I will add .xyz TLD.

**Comment by adkiller126** [comment]
@IsraeliAdblocker, 
I have a simple solution how to deal with this. Since I assume those guys also see this correspondence,   please contact me via email - easylisthebrew@gmail.com.
B.

**Comment by adkiller126** [comment]
@IsraeliAdblocker, @EasyListHebrew - Ads are still here

please block the following domains... those are the "next" domains they are planing to use (;
dascasdw.xyz - the current domain 
bostonwall.com
njkiho.info

**Comment by adkiller126** [comment]
@IsraeliAdblocker 

Back again, now -  http://vcxzv.website
Other domain you should block: 
vcx.website  dfskgjt.com  dfskgmrepts.com  njkidsrun.info  

Non-relevant any more:
kln.site  klnrew.site  rkgnmwre.site  rkg.site   asermtawlfs.xyz

**Comment by freeinternet16** [comment]
Any update with this?

**Comment by IsraeliAdblocker** [comment]
https://github.com/ABPIsrael/EasyListHebrew/commit/499ab404dd64ff14344785849a6aa2f35785caca

**Comment by freeinternet16** [comment]
Once again - csklde.space (current domain). 

@IsraeliAdblocker  Please block it. 

They just need to understand that they can't win the community! 

FI16

**Comment by IsraeliAdblocker** [comment]
I am seeing ads on ynet from the same domains, until I won't see, they will be there.

**Comment by freeinternet16** [comment]
You right. ads are still in ynet sport as well. 

why the s3 works for ynet and not for globes?

**Comment by adkiller126** [comment]
@IsraeliAdblocker - Please check

**Comment by adkiller126** [comment]
@IsraeliAdblocker - ??

**Comment by freeinternet16** [comment]
Once again - http://beerforthepipl.com

@IsraeliAdblocker

**Comment by adkiller126** [comment]
@IsraeliAdblocker - Please check (email)

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#21

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#119
