### ISSUE TITLE
Popups in http://www.inn.co.il/

### ISSUE THREAD

**Issue by Yaron10** [ABPIsrael/EasyListHebrew#121]
Hello,

`http://www.inn.co.il/` frequently changes its popups.
Recently they started using alternative popups if one has been blocked.

For example:
If I add the `||campusnet.zefat.ac.il^$popup,third-party` filter, another site pops up and I have to add `||bsdygital.co.il^$popup,third-party`.

Is it possible to block them all using one rule?

Thank you.

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#22

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#121
