### ISSUE TITLE
תפוז

### ISSUE THREAD

**Issue by someone900** [ABPIsrael/EasyListHebrew#42]
http://www.tapuz.co.il/forums2008/forumpage.aspx?forumid=394&r=1

שימו לב בצד שמאל יש וידיאו של פליקס שהינו פרסומת והוא מתנגן עם טעינת הדף...
בלי קשר לעובדה שאפשר לבטל ניגון וידיאו אוטומטי, הוידיאו הזה אינו חלק מהתוכן של הדף זה פרסומת

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#42
