### ISSUE TITLE
מורדו - פתרון תשחצים

### ISSUE THREAD

**Issue by atlanteh** [ABPIsrael/EasyListHebrew#54]
There's the filter you need to add:
pitaronfree.blogspot.co.il##I[id="g207"]

**Comment by EasyListIsrael** [comment]
this issue can be solved but not using this filter because the site owner can easily change the id.
the main fix won't work on firefox
i will add this filter and other that will fix this on chrome.

**Comment by atlanteh** [comment]
Still doesn't work :(

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#54
