### ISSUE TITLE
one.co.il

### ISSUE THREAD

**Issue by Efi-H** [ABPIsrael/EasyListHebrew#59]
Hi
It is possible block the "AD" in the videos ? 
ex' :
http://www.one.co.il/Cat/Video/first.aspx?c=113&id=45843

Thanks

**Comment by EasyListIsrael** [comment]
Not using adblock
בתאריך 26 בספט 2015 23:45,‏ "Efi-H" <notifications@github.com> כתב:

**Comment by Efi-H** [comment]
so.. you know with what ?

**Comment by EasyListIsrael** [comment]
it's possible with greasemonkey if you know a little JS

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#59
