### ISSUE TITLE
Ynet started harassing about adblockers

### ISSUE THREAD

**Issue by vadali** [ABPIsrael/EasyListHebrew#62]
Here is a quick solution that you might want to add.. Simply adding the following to custom removes the annoyance, however it might not be fine grained enough, I see other things (mainly commercial-like buttons) disappearing as well (which is a blessing for me personally).

    ynet.co.il##div#cboxOverlay
    ynet.co.il##div#colorbox

**Comment by EasyListIsrael** [comment]
update your filters it was already fixed

**Comment by vadali** [comment]
You'r the man! :) thanks

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#62
