### ISSUE TITLE
A new popup in Ynet

### ISSUE THREAD

**Issue by Yaron10** [ABPIsrael/EasyListHebrew#63]
Hello,

A new [popup](http://s4.postimg.org/h50dfrtrh/ynet.png) in [Ynet](http://www.ynet.co.il/home/0,7340,L-8,00.html).

Thank you for your work.

**Comment by Yaron10** [comment]
I've just updated the list. 
Sorry for not doing that before posting.

Thank you.

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#63
