### ISSUE TITLE
videos broken on http://www.one.co.il

### ISSUE THREAD

**Issue by mapx-** [ABPIsrael/EasyListHebrew#65]
http://www.one.co.il/Article/15-16/1,1,0,0/261224.html?ref=hp&obref=obinsource

Error loading playlist:
Error loading file

add
@@||one.co.il^$xmlhttprequest
@@||akamai.advsnx.net/crossdomain.xml$domain=one.co.il
@@||akamai.advsnx.net/CDN/one/jw6/plugin.swf$domain=one.co.il

from
https://adblockplus.org/forum/viewtopic.php?f=1&t=42788

**Comment by EasyListIsrael** [comment]
thanks mapx

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#65
