### ISSUE TITLE
www.Goalim4u.site

### ISSUE THREAD

**Issue by TheTomer** [ABPIsrael/EasyListHebrew#66]
http://www.goalim4u.site/
This website keeps popping up an ad block disable request.

**Comment by EasyListIsrael** [comment]
already fixed
https://github.com/ABPIsrael/EasyListHebrew/commit/e4e261b3d5df42833b73e47f7ad049e7ef74485c

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#66
