### ISSUE TITLE
News Letter popup in NRG

### ISSUE THREAD

**Issue by Yaron10** [ABPIsrael/EasyListHebrew#67]
Hello,

What should be the filter for the News Letter popup in http://www.nrg.co.il/online/HP_1.html#after_maavaron?

I'd appreciate your help.

http://s3.postimg.org/im25xb7f7/nrg.png

**Comment by EasyListIsrael** [comment]
hi this ad is self advertising so i will not block it.
if you want you can add it to your personal filter list
nrg.co.il##.fancybox-overlay.fancybox-overlay-fixed

**Comment by Yaron10** [comment]
Thank you for the prompt reply. I appreciate it.
:+1:

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#67
