### ISSUE TITLE
Annoying ads are displayed while navigating between pages in walla.co.il

### ISSUE THREAD

**Issue by kobik** [ABPIsrael/EasyListHebrew#68]
Url example of one of the displayed ad http://x.walla.co.il/banners/ad_frames/adt_c.html?Fusionclick=http://fus.walla.co.il/event/igtqy/mint.new_walla.sports.basketball.euroleague.article/3941914530/click?url=http://rep.erate.co.il/t:rep;pid:18135;tid:18531;perId:0

**Comment by EasyListIsrael** [comment]
what browser?

**Comment by SMed79** [comment]
`||x.walla.co.il^`
https://reports.adblockplus.org/296b3d78-4dae-46d7-9213-aa50464829fa#tab=all

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#68
