### ISSUE TITLE
mako adblock warning removal on vod

### ISSUE THREAD

**Issue by naglot** [ABPIsrael/EasyListHebrew#69]
trying to watch some episodes on makovod but they ask me to remove my adblock
how to reproduce:
1.enter http://www.mako.co.il/mako-vod
2.select any content
3.cry :(

**Comment by rafi-mellanox** [comment]
fixed
update your filter lists

**Comment by EasyListIsrael** [comment]
fixed
update your filters

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#69
