### ISSUE TITLE
ads are visible on jobmaster.co.il

### ISSUE THREAD

**Issue by geostant** [ABPIsrael/EasyListHebrew#71]
A big banner on the left that always being showed and another banner on the top that not in all the reloads been showed.

**Comment by rafi-mellanox** [comment]
it is a banner but it's considered self advertisement so i think i won't block it

**Comment by EasyListIsrael** [comment]
it is a banner but it's considered self advertisement so i think i won't block it

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#71
