### ISSUE TITLE
Please modify date format for "Last Modified:"

### ISSUE THREAD

**Issue by RamKromberg** [ABPIsrael/EasyListHebrew#72]
Could you please change the date-format so instead of:
<code>Last modified: 06/01/16 10:56</code>
It will be (assuming GMT+2 Israel Standard Time):
<code>Last modified: 06 Jan 2016 08:56 UTC</code>

While I admit it's not ISO 8601 either way, the established convention used by AdblockPlus and EasyList indicates the actual time relative to UTC\GMT and will help resolve https://bugs.launchpad.net/midori/+bug/1531585 .

**Comment by EasyListIsrael** [comment]
if it will be 11 Jan 2016 09:42 without the UTC will it be ok?

**Comment by RamKromberg** [comment]
I think "11 Jan 2016 09:42 IST" or maybe "11 Jan 2016 09:42 UTC+2" would be more correct but I have no idea since I'm not familiar with this convention or the code that parses it in Midori.

**Comment by EasyListIsrael** [comment]
i uploaded a tmp commit please check and return with an answer so i can close the issue

**Comment by RamKromberg** [comment]
Lol too slow :D

**Comment by EasyListIsrael** [comment]
I'll let you finish it as it should
send me a new pull request and change this file
https://github.com/ABPIsrael/EasyListHebrew/blob/master/tools/addChecksum.py
look in line 39
you should change it to something like  %d %m %y %H:%M
you can read about this function here (are you a developer?)
https://docs.python.org/2/library/time.html#time.strftime

**Comment by EasyListIsrael** [comment]
check now
https://github.com/ABPIsrael/EasyListHebrew/commit/a3116bf2ec97fbc0cb018a700347c3718bfda6c7

**Comment by RamKromberg** [comment]
Nah still segfaults. It wasn't the checksum. It's the year. It needs 4 digits. Try using capital %Y as in:
<code>data = re.sub(dateRegexp, '! Last modified: '+time.strftime('%d %b %Y %H:%M\n'), data)</code>

Also, you can use the following to produce the full "correct" time signature:
<code>import datetime</code>
<code>datetime.datetime.utcnow().strftime('%d %b %Y %H:%M UTC')</code>

I don't have a python interpreter installed on this machine so I'll look at the whole script later and will try getting the whole thing working properly.

**Comment by RamKromberg** [comment]
Oh nice you've got it working now :) There's still a mysterious segfault when restarting the browser but now it doesn't segfault as soon as the list is inserted into the gui so that's a step forward in the right direction :dancer:

But that should be a separate (still unknown( issue so I'll close this one.

Thanks :)

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#72
