### ISSUE TITLE
YNET Movie FF / FR / Seconds selection is blocked when a AdBlocker is turned on.

### ISSUE THREAD

**Issue by Nachmani** [ABPIsrael/EasyListHebrew#75]
You can't change and skip in video playing during a surf in www.ynet.co.il. if you wish to do so, you need to un-block your adblocker and than all the junk comes back in.

please someone find a solution for this. 

tnx

Nachmani

**Comment by EasyListIsrael** [comment]
this was fixed a while ago
https://github.com/ABPIsrael/EasyListHebrew/commit/4f3a6ecc510b195da87b7e6a3f8b4a506edac8ac
please update your list and check again
also what browser extension are you using?

**Comment by Nachmani** [comment]
Chrome browser.
Will check the updated link you sent.
Tnx in advance for your assistance and time,

Hagai Nachmani

Sent by MailWise – See your emails as clean, short chats.

-------- Original Message --------

**Comment by Nachmani** [comment]
Hi thanks for your reply,but the web page you sent me too included lots of script and text to manually edit .
sadly I'm not familiar with scripting and just request the link for already a "closed package" and already a easy file to use on my browser (Chrome).
is there such file (already compiled and closed so I just have to double click it ?)

Hagai Nachmani
+972-54-8191888Jerusalem, Israel

Date: Sun, 17 Jan 2016 23:29:33 -0800

**Comment by EasyListIsrael** [comment]
find the adblock extension in your chrome toolbar right click on it an press options and than press update now or press on the upper toolbar on lists and then update now.

**Comment by Nachmani** [comment]
Thank you!
i've done all of this (please see attached picture).
do you recommand perhaps on another version of adblock I need to install? 
if not, I don't wish to waist your time too much, I will manage some other way.
thanks again,
Hagai Nachmani+972-54-8191888Jerusalem, Israel

Date: Mon, 18 Jan 2016 02:19:30 -0800

**Comment by EasyListIsrael** [comment]
there is no picture attached

**Comment by Nachmani** [comment]
![capture](https://cloud.githubusercontent.com/assets/16753146/12396349/9b836904-be0f-11e5-89d4-16ab6cafebaa.JPG)

**Comment by Nachmani** [comment]
thanks in advance

**Comment by EasyListIsrael** [comment]
go to filter-lists on the top and press update
also add a print screen

**Comment by Nachmani** [comment]
![capture](https://cloud.githubusercontent.com/assets/16753146/12396749/c948aa0a-be11-11e5-83b9-a6dbdef492df.JPG)

**Comment by EasyListIsrael** [comment]
you are not subscribe the the hebrew list
choose from the select language Hebrew

**Comment by Nachmani** [comment]
Awesome !!  works like a charm! never knew I had to do that....
thanks man! you saved me tons of hours .. (literally! ) :)

**Comment by EasyListIsrael** [comment]
:+1: :)
