### ISSUE TITLE
new ads are shown on ynet

### ISSUE THREAD

**Issue by vadali** [ABPIsrael/EasyListHebrew#76]
seems to have div id "ads.ozen.right"

adding `ynet.co.il#div(id^=ads)` to custom seems to fix it for now..

**Comment by EasyListIsrael** [comment]
please attach picture
also read this
http://malwaretips.com/blogs/randomprice-removal/
http://malwaretips.com/blogs/related-searches-virus/
https://easylist.adblockplus.org/blog/2013/03/09/ads-caused-by-malware-or-adware-extensions-or-plugins

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#76
