### ISSUE TITLE
Ynet.co.il bypasses ABP with a script from d2pxb4n3f9klsc.cloudfront.net

### ISSUE THREAD

**Issue by codemorpher** [ABPIsrael/EasyListHebrew#78]
Hi!
I report here the problem reported on http://forums.lanik.us/viewtopic.php?f=62&t=28238

This is how Ynet with ads looks on Linux's chrome:
[(https://i.imgsafe.org/6781726.jpeg)]

Although, the problem seems to belong to not only hebrew list, it would be nice to solve it on Ynet right now.

**Comment by EasyListIsrael** [comment]
https://github.com/ABPIsrael/EasyListHebrew/commit/22b4667a736ba661b6c710cba44af6348fd013c2

**Comment by EasyListIsrael** [comment]
you want this to be fixed in other ynet sites? in the hebrew site it fixed, you just need to update your list

**Comment by codemorpher** [comment]
Oh, great! Just did not update the list! Thanks!

**Comment by AdHelper** [comment]
new Ynet ads domains:
http://goodluckblockingthis.com
http://d2bj2texxib1qg.cloudfront.net
http://d1clufhfw8sswh.cloudfront.net/id.js?accountId=7328841
http://goodluckblockingthis.com/scripts/ynetarticle/production/jquery.min.js

image:
https://goo.gl/RRk2Du

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#78
