### ISSUE TITLE
http://www.bhol.co.il/ forums

### ISSUE THREAD

**Issue by bannana123** [ABPIsrael/EasyListHebrew#81]
The extension also blocks comments that are not advertisements.

**Comment by EasyListIsrael** [comment]
Already fixes update the list
https://github.com/ABPIsrael/EasyListHebrew/commit/79031da91d818520c2134e0aa346800ca6058f3c

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#81
