### ISSUE TITLE
Walla should be updated

### ISSUE THREAD

**Issue by Yaron10** [ABPIsrael/EasyListHebrew#82]
Hello,

Could you please update this page?
http://tv-guide.walla.co.il/

Thank you.

**Comment by EasyListIsrael** [comment]
i don't see any problem

**Comment by IsraeliUser** [comment]
fixed
https://github.com/ABPIsrael/EasyListHebrew/commit/6369f99a16e9975ffcc83f1a4c135c751abf5303

**Comment by Yaron10** [comment]
Thank you. I appreciate your great work.

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#82
