### ISSUE TITLE
Ynet Shopmarket Ads

### ISSUE THREAD

**Issue by AdHelper** [ABPIsrael/EasyListHebrew#83]
I'm using the newest hebrewList + easyList with adblock Plus and I am getting the shopmarket ads on ynet.
[https://goo.gl/5zwg2Z](https://goo.gl/5zwg2Z)

**Comment by IsraeliUser** [comment]
Mostly self promotion, so I don't think it would be blocked.

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#83
