### ISSUE TITLE
HebrewList for IE 11?

### ISSUE THREAD

**Issue by AdHelper** [ABPIsrael/EasyListHebrew#84]
Is there any way to add hebrew list on IE 11?
on https://www.microsoft.com/en-us/iegallery I can only see Privacy List and Indonesian EasyList.

**Comment by EasyListIsrael** [comment]
https://adblockplus.org/en/internet-explorer

**Comment by EasyListIsrael** [comment]
enable

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#84
