### ISSUE TITLE
Ynet New Ads

### ISSUE THREAD

**Issue by AdHelper** [ABPIsrael/EasyListHebrew#85]
new Ynet ads domains:
goodluckblockingthis.com
d2bj2texxib1qg.cloudfront.net
d1clufhfw8sswh.cloudfront.net/id.js?accountId=7328841
goodluckblockingthis.com/scripts/ynetarticle/production/jquery.min.js

image:
https://goo.gl/RRk2Du

**Comment by EasyListIsrael** [comment]
where are the ads?
i don't see them

**Comment by AdHelper** [comment]
there are some outbrain ads on the right side and down after the article.

**Comment by IsraeliUser** [comment]
You can use uBlock Origin which blocks Outbrain and Taboola completely by default (blocks both ads and non-ads). Just make sure you subscribed to EasyList Hebrew.

To get rid of Outbrain and Taboola ads using ABP, uncheck the option "Allow some non-intrusive advertising" on ABP Filter Preferences. You will see only their non-advertisement links. Taboola pays ABP for unblocking their ads by default :( . Outbrain ads are being unblocked on some sites, but not on ynet. I see only non-ads Outbrain links there.

**Comment by AdHelper** [comment]
I am using adblock Plus with "Allow some non-intrusive advertising" off and I can still see the outbrain full ads, I think this is because this script: goodluckblockingthis.com/scripts/ynetarticle/production/jquery.min.js

you can see that there is: var outbrain = true; there.

**Comment by IsraeliUser** [comment]
Which browser do you use?

**Comment by AdHelper** [comment]
Chrome 49 on Mac osx

**Comment by xqgex** [comment]
I'm also seeing those ads,
In the bottom part of any article there is "אולי יעניין אותך גם " section
Sometime you will see an ads that disguise herself as an article, The visual way to know the difference is that those ads have a text on the image that say 'מרחבי הרשת"
![screenshot from 2016-03-12 23 32 53](https://cloud.githubusercontent.com/assets/15404/13725450/cf3fa828-e8aa-11e5-834b-3b88caec85bc.png)

**Comment by freeinternet16** [comment]
I'm also seeing those ads! 

please add the http://goodluckblockingthis.com domain to the blcak list (let's show them we're lucky ;\)

it was worked for me. 

![unnamed](https://cloud.githubusercontent.com/assets/17808973/13727866/7fa35eb0-e90c-11e5-9412-d3526cca6da5.png)

**Comment by IsraeliUser** [comment]
Fixed:
https://github.com/ABPIsrael/EasyListHebrew/commit/4752581c5af4c0f00dfa9574381da8d4e1b7df97

**Comment by freeinternet16** [comment]
Great!!!!

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#85
