### ISSUE TITLE
haaretz

### ISSUE THREAD

**Issue by ShalomP** [ABPIsrael/EasyListHebrew#87]
כדי לשחרר את החסימה של הארץ למי שמפעיל חוסם פרסומות הוספתי את השורה הבאה אצלי:
www.haaretz.co.il/htz/js/resp/minified/header-scripts-int.js
אני מניח שזה משפיע השפעות נוסת אבל מינוריות.
כדאי להוסיף את זה, או גירסה טובה יותר.

**Comment by IsraeliUser** [comment]
Fixed:
https://github.com/ABPIsrael/EasyListHebrew/commit/b8cf33d8c3cbeb2c175305c61c2951b33ca9d388

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#87
