### ISSUE TITLE
Walla.co.il site suggest to add itself to the filter lists. ( via confirm)

### ISSUE THREAD

**Issue by RoyiNamir** [ABPIsrael/EasyListHebrew#89]

**Comment by AdHelper** [comment]
same here, they are using a weakness in Adblock which will also them to subscribe to a custom filter.

**Comment by IsraeliUser** [comment]
They are using a weakness/bug in Adblock. 
Adblock Plus and uBlock Origin are not affected. More info: https://issues.adblockplus.org/ticket/2426
Please report a bug here: https://help.getadblock.com/support/tickets/new

**Comment by gorhill** [comment]
> Adblock Plus and uBlock Origin are not affected.

They would be affected as well if the site cared to detect them.

If I enable uBlock Origin ("uBO") along with AdBlock, uBO is also fooled into offering to add the filter list -- although in uBO's case this accomplishes nothing since it does not support whitelisting through the `document` filter option -- which is what the filter list does. I still need to address this.

**Comment by IsraeliUser** [comment]
I think this issue have been solved in Adblock Plus: https://github.com/adblockplus/adblockpluschrome/compare/master...kzar:2426-block-suspicious

**Comment by RoyiNamir** [comment]
I'm using adblock not ABP.

**Comment by AdHelper** [comment]
As the great gorill said, this weakness will work if they will also detect ABP or Ublock, they are just testing this I think and they are detecting Adblock only.
this should be handled asap or we will see this everywhere.

**Comment by kzar** [comment]
@IsraeliUser The change you linked to is actually just something I was experimenting with, it never ended up in Adblock Plus. (Instead of blocking Ajax requests to our web accessible resources we just removed all of our web accessible resources!)

**Comment by AdHelper** [comment]
and this is only in order to detect adblock, this is not a fix for the weakness.

**Comment by kzar** [comment]
FYI https://hg.adblockplus.org/adblockpluschrome/rev/4d845c1d2115

**Comment by AdHelper** [comment]
this fix is only for ABP, what about regular Adblock?

**Comment by EasyListHebrew** [comment]
i checked it with chrome + adblock and it's fixed
try removing cookies (try incognito window) 
i couldn't reproduce the issue with ADP

**Comment by AdHelper** [comment]
still there:
https://goo.gl/sxwtWL

adblock version: 2.52 latest.

**Comment by EasyListHebrew** [comment]
did you add the filter to your customize list?
||walla.co.il/resources/js/combine
see in adblock how to add personal filters

**Comment by AdHelper** [comment]
working good, why this is not on the hebrew list?!

**Comment by EasyListHebrew** [comment]
it is but adblock takes the list from a generated list made by easylist and hebrew list
and it's generated every few hours
i think now it's pushed 
https://easylist-downloads.adblockplus.org/israellist+easylist.txt

**Comment by EasyListHebrew** [comment]
this commit breaks all the links in the site

**Comment by AdHelper** [comment]
any other possible solution?

**Comment by EasyListHebrew** [comment]
no

**Comment by AdHelper** [comment]
looks like the problem is fixed now for some strange reason, there was any change in adblock?

**Comment by RoyiNamir** [comment]
Wait so now i should update Adblock and then everything will work without alerting the user to add itself to filter list ?

**Comment by AdHelper** [comment]
yes, please confirm.

**Comment by RoyiNamir** [comment]
Yes. All ok. though , now it shows "pop up blocked" in address bar but that's nothing.

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#89
