### ISSUE TITLE
פרסומות בגלובס

### ISSUE THREAD

**Issue by almog123** [ABPIsrael/EasyListHebrew#91]
אני משתמש באדבלוק פלוס הכי חדש והכי מעודכן עם היברו ליסט.
ואני מקבל פרסומות בגלובס
![globes.png](https://cloud.githubusercontent.com/assets/17848148/13905660/fee9f6da-eece-11e5-8f5c-f327f13ac80a.png)

**Comment by EasyListHebrew** [comment]
https://github.com/ABPIsrael/EasyListHebrew/issues/90

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#91
