### ISSUE TITLE
כלכליסט Outbrain

### ISSUE THREAD

**Issue by freeinternet16** [ABPIsrael/EasyListHebrew#93]
שוב אותה שיטה כמו ב- ynet
תוכלו לחסום בבקשה את הדומיין 
http://goodluckblockingthis.com

תודה

**Comment by AdHelper** [comment]
same here:
screenshot: https://goo.gl/ngzryf

**Comment by almog123** [comment]
זה עדיין ככה, מתי תתקנו את זה?

**Comment by almog123** [comment]
עובד! תודה
