### ISSUE TITLE
Report: Ad not blocked

### ISSUE THREAD

**Issue by talking2wall** [ABPIsrael/EasyListHebrew#94]
Please check this site: https://www.fxp.co.il/ .
There's an ad that is not blocked and I would be happy if you will be able to fix this.

Thanks in advance.

**Comment by dukduk1** [comment]
i almost reported  about it now, but i see you already reported.
this site is need special block about ads, they every time is bypass the blocks we report.
plz block this ad  i see it also.

**Comment by almog123** [comment]
what about:
`||images.fxp.co.il/ad*`
seems better

**Comment by EasyListIsrael** [comment]
no

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#94
