### ISSUE TITLE
pop and ads not blocked

### ISSUE THREAD

**Issue by nimi3434** [ABPIsrael/EasyListHebrew#96]
in this site:
[https://www.fxp.co.il/](https://www.fxp.co.il/)

on this page:
[https://www.fxp.co.il/showthread.php?t=16812592](https://www.fxp.co.il/showthread.php?t=16812592)

I got banner ad on the side, and pop up jump to me also
![image](https://cloud.githubusercontent.com/assets/18309029/14320314/423fad02-fc1d-11e5-8c7d-ace444c3a349.png)

**Comment by AdHelper** [comment]
same here.

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#96
