### ISSUE TITLE
ads in ynet homepage

### ISSUE THREAD

**Issue by nimi3434** [ABPIsrael/EasyListHebrew#97]
![image](https://cloud.githubusercontent.com/assets/18309029/14324484/a3059ff6-fc2d-11e5-8c46-29734e5649b3.png)

**Comment by almog123** [comment]
same here, I can confirm.

**Comment by AdHelper** [comment]
same here.

**Comment by AdHelper** [comment]
`ynet.co.il###promolightboxmvc-2`

**Comment by EasyListIsrael** [comment]
i think i'll allow it

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#97
