### ISSUE TITLE
Ads are back to globes.co.il

### ISSUE THREAD

**Issue by almog123** [ABPIsrael/EasyListHebrew#98]
since the last update of the hebrew list when you dropped 
`||s3.amazonaws.com^$domain=globes.co.il`
ads are back on globes.co.il.

**Comment by AdHelper** [comment]
I don't know why you removed this rule, the only script that is made from globes.co.il to amazon domain is a script that is related to their anti Adblock.
seems like something very shady is going on here.

**Comment by AdHelper** [comment]
I don't know why you removed this rule, the only script that is made from globes.co.il to amazon domain is a script that is related to their anti Adblock.
seems like something very shady is going on here.
this is their anti adblock script:
https://s3.amazonaws.com/altlkqlbn7alkclszarbca7zcnqibtkk6kaabjbrccgaaa/altlkqlbn7alkclszarbca7zcnqibtkk6kaabjbrccgaaa

seems like altlkqlbn7alkclszarbca7zcnqibtkk6kaabjbrccgaaa is a random

**Comment by EasyListIsrael** [comment]
this filter caused the site not to work well when opening some articles 
i need to find another filter

**Comment by EasyListIsrael** [comment]
i don't see any ads what browser+ adblocker (ADP\adblock\ublock) are you using?

**Comment by almog123** [comment]
Adlock plus - chrome.
ads are coming from some kind of xyz domain (seems like a random like before).
you should at least block https://s3.amazonaws.com/altklxqlbn7alnwlszarbcnwzcnqibtlll6kaabjbswcgaaa

**Comment by AdHelper** [comment]
I've just tested ||s3.amazonaws.com^$domain=globes.co.il rule on inner pages, I can't seem to find any problem, please provide the details so I can create the right rule to whitelist.

**Comment by EasyListIsrael** [comment]
on firefox with ADP with this rule enabled i just opened a few random articles and some of them show blank pages. and a #hp... is added to the end of the url

**Comment by AdHelper** [comment]
I've found the issue.

**Comment by EasyListIsrael** [comment]
this should fix it please check
||xyz^$subdocument,domain=globes.co.il

**Comment by AdHelper** [comment]
new domain: faweprsdf.pw

**Comment by EasyListIsrael** [comment]
https://easylist.adblockplus.org/blog/2013/05/10/anti-adblock-guide-for-site-admins

**Comment by EasyListIsrael** [comment]
https://github.com/ABPIsrael/EasyListHebrew/commit/8eb6a168e81a81478e55e4ed4e5311b357d405d4

**Comment by AdHelper** [comment]
ads are still there...

**Comment by AdHelper** [comment]
working perfect, thank you!

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#98
