### ISSUE TITLE
Ads not blocked on Calcalist.co.il

### ISSUE THREAD

**Issue by MMoamm** [ABPIsrael/EasyListHebrew#99]
Some ads are not blocked on Calcalist. For example, on the top of this page:

http://www.calcalist.co.il/internet/articles/0,7340,L-3685575,00.html

I've just updated all filters and added Hebrew filters, but the problem persists.
Any idea why?

**Comment by AdHelper** [comment]
can't see any ads, please remove hebrew list subscribe and then resubscribe again, still persist?

**Comment by MMoamm** [comment]
I've blocked the specific ad on this page, so I can't see it anyway.
But on any other page on this website, for instance:
http://www.calcalist.co.il/markets/articles/0,7340,L-3685622,00.html
http://www.calcalist.co.il/markets/articles/0,7340,L-3685569,00.html
and any other page, the problem persists.
I've tried Adblock, removed & reinstalled Hebrew filters.
Have done the same on AdblockPlus.
No results, still spammy ads.
Any idea?

**Comment by freeinternet16** [comment]
אותו דבר גם לי...
 

<img width="754" alt="capture" src="https://cloud.githubusercontent.com/assets/17808973/14462002/adb48f44-00cd-11e6-9ba9-dc4089168f75.PNG">

**Comment by freeinternet16** [comment]
Work only on Adblock - not for ABP
please check

**Comment by AdHelper** [comment]
still nothing for me on http://www.calcalist.co.il/internet/articles/0,7340,L-3685575,00.html
this is only for regular adblock?

**Comment by EasyListIsrael** [comment]
i tried both
please try removing the extension and reinstalling it

**Comment by EasyListHebrew** [comment]
This issue was moved to easylist/EasyListHebrew#100
